includedir=$(prefix)/include

build:

install: $(includedir)/rpiozhogin2012.H

$(includedir)/rpiozhogin2012.H: rpiozhogin2012.H
	cp rpiozhogin2012.H $(includedir)

uninstall:
	- rm -f $(includedir)/rpiozhogin2012.H

clean:
